[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "apache2-foreground"
healthcheckPath = "/s/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[services.mautic-web]
name = "Mautic Web"
build = { dockerfilePath = "Dockerfile" }
image = "mautic/mautic:5-apache"

env = {
    DOCKER_MAUTIC_ROLE = "mautic_web",
    MAUTIC_DB_HOST = "${{MySQL.MYSQLHOST}}",
    MAUTIC_DB_PORT = "${{MySQL.MYSQLPORT}}",
    MAUTIC_DB_NAME = "${{MySQL.MYSQLDATABASE}}",
    MAUTIC_DB_USER = "${{MySQL.MYSQLUSER}}",
    MAUTIC_DB_PASSWORD = "${{MySQL.MYSQLPASSWORD}}",

    # Optional PHP tuning
    PHP_INI_VALUE_DATE_TIMEZONE = "UTC",
    PHP_INI_VALUE_MEMORY_LIMIT = "512M",
    PHP_INI_VALUE_UPLOAD_MAX_FILESIZE = "512M",
    PHP_INI_VALUE_POST_MAX_FILESIZE = "512M",
    PHP_INI_VALUE_MAX_EXECUTION_TIME = "300",

    # Run DB migrations automatically on first start
    DOCKER_MAUTIC_RUN_MIGRATIONS = "true",
    
    # Debug settings
    PHP_INI_VALUE_DISPLAY_ERRORS = "On",
    PHP_INI_VALUE_ERROR_REPORTING = "E_ALL",
    PHP_INI_VALUE_LOG_ERRORS = "On",
    PHP_INI_VALUE_ERROR_LOG = "/var/www/html/var/logs/php_errors.log"
}

ports = [80]

[services.mysql]
name = "MySQL Database"
image = "mysql:8"  # use mysql:8 for compatibility with Mautic 5
env = {
    MYSQL_DATABASE = "mautic",
    MYSQL_USER = "mautic",
    MYSQL_PASSWORD = "${{MySQL.MYSQLPASSWORD}}",
    MYSQL_ROOT_PASSWORD = "${{MySQL.MYSQL_ROOT_PASSWORD}}"
}
volumes = ["mysql_data:/var/lib/mysql"]

[volumes]
mysql_data = { mountPath = "/var/lib/mysql" }
