[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[services.mautic-web]
name = "Mautic Web"
build = { dockerfilePath = "Dockerfile" }
env = { DOCKER_MAUTIC_ROLE = "mautic_web" }
ports = [80]
# Railway only allows one volume per service. Persist config only.
volumes = ["mautic_config:/var/www/html/app/config"]

[services.mysql]
name = "MySQL Database"
image = "mysql:8"
env = {
    MYSQL_DATABASE = "mautic",
    MYSQL_USER = "mautic",
    MYSQL_PASSWORD = "yourpassword",
    MYSQL_ROOT_PASSWORD = "yourrootpassword"
}
volumes = ["mysql_data:/var/lib/mysql"]

[volumes]
mysql_data = { mountPath = "/var/lib/mysql" }
mautic_config = { mountPath = "/var/www/html/app/config" } 